### ISSUE TITLE
Foundations excercises: Modify excercise 5 for child combinators

### ISSUE THREAD

**Issue by Shadow5634** [TheOdinProject/css-exercises#345]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

[Excercise 5](https://github.com/TheOdinProject/css-exercises/tree/main/foundations/05-descendant-combinator) of foundations deals with the descendant combinator. However, for people who are familiar with other combinator types, using child combinators also seems to solve this question. This may be considered as a viable solution or even an incorrect solution depending on how one sees it. The latter might be more correct since the [README.md](https://github.com/TheOdinProject/css-exercises/tree/main/foundations/05-descendant-combinator#descendant-combinator) mentions that we must modify the `p` elements that are _descendants_ of `div` elements (making the descendant combinator the more apt choice).

As a result we could add in the solution.css file that using the child combinator, while giving the intended result, is incorrect.
Another option could be to modify the question with more nesting (via lists where each element is a para or something else that has been covered in the curriculum so far) to show that any level of descendants should also be modified through css.

**2. Acceptance Criteria:**

**3. Additional Information:**

```[tasklist]
### Tasks
```

**Comment by CouchofTomato** [comment]
@codyloyd Would you take a look at this please.

**Comment by CouchofTomato** [comment]
Closing if there isn't the support for this change.

Really appreciate you creating this issue @Shadow5634.
